/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Leonardo Carvalho (https://sketchfab.com/livrosparacriancas)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/demon-wings-11-low-poly-animated-8ef7580f1f1a48c488a8bbcf61067bc5
Title: Demon Wings 1.1 (Low poly - Animated)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const DragonWings = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/demon_wings.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Demon_Wingsfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Demon_Wings_Rig"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_49"
                      geometry={nodes.Object_49.geometry}
                      material={materials['Demon_Wings.002']}
                      skeleton={nodes.Object_49.skeleton}
                    />
                    <group name="Object_48" />
                  </group>
                </group>
                <group name="Demon_WIngs" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
export default DragonWings

useGLTF.preload('/models/demon_wings.glb')
